Repository Career-Mate/Web, pull requests merged in 2025-01, with the labels that each got.

#6 [Feat] Job 컴포넌트 구현
  src/App.jsx
  src/components/Job/Job.jsx
  src/components/Job/styled/styled.js
Labels: enhancement

#8 [Feat] ProfileInput 컴포넌트 구현
  src/App.jsx
  src/components/Input/ProfileInput.jsx
  src/components/Input/styled/styled.js
Labels: enhancement

#4 [Feat] Button 컴포넌트 구현
  src/components/Button/LogoutButton/LogoutButton.jsx
  src/components/Button/LogoutButton/styled/styled.js
  src/components/Button/OvalButton/OvalButton.jsx
  src/components/Button/OvalButton/styled/styled.js
  src/components/Button/SquareButton/SquareButton.jsx
  src/components/Button/SquareButton/styled/styled.js
  src/test/Test.jsx
Labels: enhancement

#12 [Feat] Navbar 컴포넌트 구현
  src/components/Menu/Navbar/Navbar.jsx
  src/components/Menu/Navbar/styled/styled.js
  src/layout/RootLayout.jsx
  src/pages/HomePage.jsx
Labels: enhancement

#16 [Feat] Footer 컴포넌트 구현
  src/App.jsx
  src/assets/career-mate.png
  src/assets/career-mate.svg
  src/assets/career-summary.png
  src/assets/job-search.png
  src/assets/logo.png
  src/assets/my-career.png
  src/components/Footer/Footer.jsx
  src/components/Footer/styled/styled.js
  src/components/Job/Job.jsx
  src/components/Job/styled/styled.js
  src/components/Menu/Navbar/Navbar.jsx
  src/layout/RootLayout.jsx
  src/layout/styled/styled.js
  src/pages/HomePage.jsx
Labels: enhancement

#22 [Feat] Button 컴포넌트 구현(추가 수정)
  src/components/Button/OvalButton/OvalButton.jsx
  src/components/Button/OvalButton/styled/styled.js
  src/components/Button/SquareButton/SquareButton.jsx
  src/components/Button/SquareButton/styled/styled.js
Labels: duplicate

#10 [Feat] ContentCard 컴포넌트 구현
  src/assets/scrap-check.svg
  src/assets/scrap-uncheck.svg
  src/assets/thumbnail.svg
  src/components/Card/ContentCard/ContentCard.jsx
  src/components/Card/ContentCard/styled/styled.js
  src/components/Card/JobPostingCard/JobPostingCard.jsx
Labels: enhancement

#11 [Feat] SubMenu 컴포넌트 구현
  src/components/Menu/SubMenu/SubMenu.jsx
  src/components/Menu/SubMenu/styled/styled.js
Labels: enhancement

#18 [Feat] ProgressBar 컴포넌트 구현
  src/components/ProgressBar/ProgressBar.jsx
  src/components/ProgressBar/styled/styled.js
  src/hooks/useProgressBar.js
Labels: enhancement

#9 [Feat] UserTemplate 컴포넌트 구현
  package-lock.json
  package.json
  src/assets/calendar.svg
  src/components/UserTemplate/Template.jsx
  src/components/UserTemplate/styled/styled.js
  src/hooks/useTemplateData.js
Labels: enhancement

#20 [Feat] ProfileInput 컴포넌트 구현
  src/components/common/Input/ProfileInput.jsx
  src/components/common/Input/styled/styled.js
  src/hooks/useInput.js
Labels: duplicate

#14 [feat] Pagination 컴포넌트 구현
  src/assets/Pagination/arrow-first.svg
  src/assets/Pagination/arrow-last.svg
  src/assets/Pagination/arrow-next.svg
  src/assets/Pagination/arrow-prev.svg
  src/components/common/Pagination/Pagination.jsx
  src/components/common/Pagination/styled/styled.js
Labels: enhancement

#13 [Feat] Popup 컴포넌트 구현
  src/assets/common/loader.svg
  src/components/Popups/LoadingPopup/LoadingPopup.jsx
  src/components/Popups/LoadingPopup/styled/styled.js
  src/components/Popups/LogoutPopup/LogoutPopup.jsx
  src/components/Popups/LogoutPopup/styled/styled.js
Labels: enhancement

#24 [Feat] InfoModal 컴포넌트 구현
  src/components/InfoContainer/InfoContainer.jsx
  src/components/InfoContainer/styled/styled.js
Labels: enhancement

#23 [Feat] SelectDropInput 컴포넌트 구현
  src/assets/interest-job-button.svg
  src/components/common/Input/SelectDropInput/SelectDropInput.jsx
  src/components/common/Input/SelectDropInput/styled/styled.js
  src/hooks/useSelectDrop.js
Labels: enhancement

#27 [Feat] Button 컴포넌트 구현(2차 추가 수정)
  src/components/common/Button/OvalButton/OvalButton.jsx
  src/components/common/Button/OvalButton/styled/styled.js
  src/components/common/Button/SquareButton/SquareButton.jsx
  src/components/common/Button/SquareButton/styled/styled.js
Labels: duplicate

#26 [Feat] TextTemplate 컴포넌트 구현
  src/components/common/TextTemplate/TextTemplate.jsx
  src/components/common/TextTemplate/styled/styled.js
  src/components/common/UserTemplate/Template.jsx
  src/hooks/useTemplateData.js
Labels: enhancement

#28 [Feat] ProgressBar 컴포넌트 구현(추가 수정)
  src/components/common/ProgressBar/ProgressBar.jsx
  src/components/common/ProgressBar/styled/styled.js
Labels: duplicate

#31 [Fix] UserTemplate 컴포넌트 수정
  src/components/common/UserTemplate/Template.jsx
  src/components/common/UserTemplate/styled/styled.js
  src/index.css
Labels: duplicate

#32 [Chore] InfoConatiner를 common 폴더에 넣기
  src/components/common/InfoContainer/InfoContainer.jsx
  src/components/common/InfoContainer/styled/styled.js
Labels: duplicate

#33 [Fix] 네비바 디자인 수정
  src/components/common/Menu/Navbar/styled/styled.js
Labels: duplicate

#34 [Fix] Button 컴포넌트 구현(2차 추가 수정)
  src/components/common/Button/LogoutButton/styled/styled.js
  src/components/common/Button/OvalButton/styled/styled.js
  src/components/common/Button/SquareButton/styled/styled.js
Labels: duplicate

#49 [Fix] Footer 수정 및 Template 콘솔 에러 해결
  src/components/common/Footer/styled/styled.js
  src/components/common/UserTemplate/styled/styled.js
Labels: duplicate

#37 [Fix] Navbar 로고 이미지 변경 및 좌우 마진 수정
  src/assets/common/career-mate.svg
  src/components/common/Menu/Navbar/Navbar.jsx
  src/components/common/Menu/Navbar/styled/styled.js
  src/hooks/useAuth.js
Labels: duplicate

#51 [Fix] ProgressBar 컴포넌트 구현(2차 추가 수정)
  src/components/common/ProgressBar/styled/styled.js
Labels: duplicate

#38 [Feat] (Page) MainPage 구현
  src/App.jsx
  src/assets/MainPage/books.svg
  src/assets/MainPage/boy.svg
  src/assets/MainPage/check-icon.svg
  src/assets/MainPage/girl.svg
  src/assets/MainPage/main-vector.svg
  src/assets/MainPage/note.svg
  src/assets/MainPage/search.svg
  src/assets/common/cm.svg
  src/components/MainPage/Card/Card.jsx
  src/components/MainPage/Card/styled/styled.js
  src/components/MainPage/CheckTextBox/CheckTextBox.jsx
  src/components/MainPage/CheckTextBox/styled/styled.js
  src/components/MainPage/InterviewBox/InterviewBox.jsx
  src/components/MainPage/InterviewBox/styled/styled.js
  src/pages/Main/MainPage/MainPage.jsx
  src/pages/Main/MainPage/styled/styled.js
Labels: enhancement

#41 [Fix] InfoContainer 수정
  src/components/common/InfoContainer/InfoContainer.jsx
  src/components/common/InfoContainer/styled/styled.js
Labels: duplicate

#42 [Fix] Pagination 컴포넌트 수정
  src/assets/Pagination/arrow-next.svg
  src/assets/Pagination/arrow-prev.svg
  src/components/common/Pagination/Pagination.jsx
  src/components/common/Pagination/styled/styled.js
Labels: duplicate

#62 [FEAT] Button 컴포넌트 구현(4차 추가 수정)
  src/components/common/Button/UnderlineButton/UnderlineButton.jsx
  src/components/common/Button/UnderlineButton/styled/styled.js
Labels: duplicate

#39 [Feat] (Page) RecommendContentPage 구현
  src/components/Recommend/JobBox/JobBox.jsx
  src/components/Recommend/JobBox/styled/styled.js
  src/pages/RecommendContentPage/RecommendContentPage.jsx
  src/pages/RecommendContentPage/styled/styled.js
  src/pages/RecommendContentPage/userData.js
Labels: enhancement

#45 [Feat] RecommendMainPage 구현
  src/App.jsx
  src/pages/Recommend/RecommnedMainPage/RecommendMainPage.jsx
Labels: enhancement

#63 [Feature] Template들 전체 삭제 버튼 추가
  src/components/common/TextTemplate/TextTemplate.jsx
  src/components/common/TextTemplate/styled/styled.js
  src/components/common/UserTemplate/Template.jsx
  src/components/common/UserTemplate/styled/styled.js
  src/hooks/useTemplateData.js
Labels: enhancement

#46 [Feat] CareerMainPage 구현
  src/App.jsx
  src/assets/MainPage/search.svg
  src/components/common/Popups/LoadingPopup/styled/styled.js
  src/components/common/Popups/LogoutPopup/styled/styled.js
  src/pages/Career/CareerMainPage/CareerMainPage.jsx
  src/pages/Career/CareerMainPage/styled/styled.js
Labels: enhancement

#43 [Feat] CareerSavePage 구현
  src/App.jsx
  src/pages/Career/CareerSavePage/CareerSavePage.jsx
  src/pages/Career/CareerSavePage/styled/styled.js
Labels: enhancement

#55 [Feat] InternExperiencePage 구현
  src/App.jsx
  src/components/common/TextTemplate/TextTemplate.jsx
  src/components/common/UserTemplate/Template.jsx
  src/data/jobTemplateData.js
  src/data/textTemplateData.js
  src/hooks/useTemplateData.js
  src/pages/Career/CareerPage/CareerNotePage.jsx
  src/pages/Career/CareerPage/styled/styled.js
  src/pages/Career/InternExperiencePage/InternExperiencePage.jsx
  src/pages/Career/InternExperiencePage/styled/styled.js
  src/pages/Career/InternExperiencePage/useInternExperience.js
Labels: enhancement

#67 [Fix] Card 오타 제거 및 onClick 함수 연결
  src/components/common/Card/ContentCard/ContentCard.jsx
  src/components/common/Card/JobPostingCard/JobPostingCard.jsx
  src/components/common/Card/styled/styled.js
Labels: duplicate

#61 [Chore] RecommendJobPage 다시
  src/App.jsx
  src/components/Recommend/JobBox/JobBox.jsx
  src/components/Recommend/JobBox/styled/styled.js
  src/components/common/Menu/Navbar/Navbar.jsx
  src/data/recommendContentData.js
  src/data/recommendJobData.js
  src/pages/Recommend/RecommendContentPage/RecommendContentPage.jsx
  src/pages/Recommend/RecommendContentPage/styled/styled.js
  src/pages/Recommend/RecommendJobPage/RecommendJobPage.jsx
  src/pages/Recommend/RecommendJobPage/styled/styled.js
  src/pages/Recommend/RecommendRouter.jsx
  src/pages/RecommendContentPage/userData.js
Labels: duplicate

#68 [Chore] Popup 수정
  src/components/common/Popups/AccountPopup/AccountPopup.jsx
  src/components/common/Popups/AccountPopup/styled/styled.js
Labels: duplicate

#69 [Chore] RecommendMainPage 수정
  src/components/common/Popups/LoadingPopup/styled/styled.js
  src/pages/Recommend/RecommnedMainPage/RecommendMainPage.jsx
Labels: duplicate

#30 [Feat] (Page) JobDetailPage 구현
  src/assets/JobDetailPage/check.svg
  src/assets/JobDetailPage/company.svg
  src/components/Recommend/JobDetailList/JobDetailList.jsx
  src/components/Recommend/JobDetailList/styled/styled.js
  src/data/JobDetailMockData.js
  src/pages/Recommend/JobDetailPage/JobDetailPage.jsx
  src/pages/Recommend/JobDetailPage/styled/styled.js
  src/pages/Recommend/RecommendContentPage/RecommendContentPage.jsx
Labels: enhancement

#59 [Feat] (page) SmartPlanner Page 구현
  package-lock.json
  src/App.jsx
  src/assets/common/book-icon.svg
  src/assets/common/speech-bubble.svg
  src/components/SmartPlanner/SmartPlanner.jsx
  src/components/SmartPlanner/styled/styled.js
  src/components/SmartPlanner/useSmartPlanner.js
  src/components/common/Input/CalendarInput/CalendarInput.jsx
  src/components/common/Input/CalendarInput/styled/styled.js
  src/components/common/Input/ProfileInput.jsx
  src/components/common/Menu/SubMenu/SubMenu.jsx
  src/components/common/Menu/SubMenu/styled/styled.js
  src/components/common/TextTemplate/TextTemplate.jsx
  src/data/smartTemplateData.js
  src/hooks/useTemplateData.js
  src/pages/MyCareer/MyCareerPage/MyCareerPage.jsx
  src/pages/MyCareer/MyCareerPage/styled/styled.js
  src/pages/MyCareer/SmartPlannerPage/SmartPlannerPage.jsx
  src/pages/MyCareer/SmartPlannerPage/styled/styled.js
Labels: enhancement

#71 [Fix] (Page) RecommendContentPage 구현
  src/pages/Recommend/RecommendContentPage/RecommendContentPage.jsx
  src/pages/Recommend/RecommendContentPage/styled/styled.js
Labels: duplicate

#66 [Feat] (page) ProfileSettingPage, ProfileEditPage 구현
  src/App.jsx
  src/components/common/InfoContainer/InfoContainer.jsx
  src/components/common/Input/SelectDropInput/SelectDropInput.jsx
  src/components/common/Input/SelectDropInput/styled/styled.js
  src/components/common/ProfileSetting/ProfileSetting.jsx
  src/components/common/ProfileSetting/styled/styled.js
  src/data/profileData.js
  src/hooks/useProfile.js
  src/hooks/useSelectDrop.js
  src/pages/Main/ProfileSettingPage/ProfileSettingPage.jsx
  src/pages/Main/ProfileSettingPage/styled/styled.js
  src/pages/Main/ProfileSuccessPage/ProfileSuccessPage.jsx
  src/pages/MyCareer/ProfileEditPage/ProfileEditPage.jsx
  src/pages/MyCareer/ProfileEditPage/styled/styled.js
Labels: enhancement

#57 [Feat] (page) Login page 구현
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/assets/LoginPage/kakao.svg
  src/assets/LoginPage/naver.svg
  src/components/common/Menu/Navbar/Navbar.jsx
  src/components/common/Popups/AccountPopup/styled/styled.js
  src/hooks/useAuth.js
  src/hooks/useLogin.js
  src/hooks/useLoginPopUp.js
  src/pages/Main/LoginPage/LoginPage.jsx
  src/pages/Main/LoginPage/styled/styled.js
  src/pages/Main/LoginProgressPage/LoginProgressPage.jsx
  src/pages/Main/LoginProgressPage/styled/styled.js
  src/pages/Main/LoginSuccessPage/LoginSuccessPage.jsx
  src/store/authStore.js
Labels: enhancement

#76 [Chore] recommend 페이지들 css 수정
  src/components/Recommend/JobBox/styled/styled.js
  src/pages/Recommend/RecommendJobPage/RecommendJobPage.jsx
  src/pages/Recommend/RecommendJobPage/styled/styled.js
Labels: duplicate

#77 [Fix] 간편 로그인 백엔드 api로 수정
  src/pages/Main/LoginPage/LoginPage.jsx
  src/pages/Main/LoginPage/styled/styled.js
Labels: duplicate

#78 [Fix] MainPage 아이콘 변경
  src/assets/MainPage/book-mark.svg
  src/assets/MainPage/books.svg
  src/assets/MainPage/file.svg
  src/assets/MainPage/note.svg
  src/assets/MainPage/search.svg
  src/pages/Main/MainPage/MainPage.jsx
Labels: duplicate

#75 [Fix] (page) SmartPlanner Page 구현 (1차 수정)
  src/components/SmartPlanner/SmartPlanner.jsx
  src/components/common/Input/CalendarInput/CalendarInput.jsx
  src/components/common/Input/CalendarInput/styled/styled.js
  src/components/common/Input/ProfileInput.jsx
  src/data/smartTemplateData.js
Labels: duplicate

#79 [Feat] Footer 아이콘 출처 추가
  src/components/common/Footer/Footer.jsx
  src/components/common/Footer/styled/styled.js
Labels: duplicate

#80 [chore] RecommendJobPage 수정
  src/components/Recommend/JobBox/styled/styled.js
  src/components/common/Button/DeadlineButton/DeadlineButton.jsx
  src/components/common/Button/DeadlineButton/styled/styled.js
  src/data/recommendJobData.js
  src/pages/Recommend/RecommendJobPage/RecommendJobPage.jsx
  src/pages/Recommend/RecommendJobPage/styled/styled.js
Labels: duplicate

#74 [Feat] 스크랩
  package-lock.json
  src/App.jsx
  src/assets/common/pin.svg
  src/components/common/Card/ContentCard/ContentCard.jsx
  src/components/common/Card/JobPostingCard/JobPostingCard.jsx
  src/data/recommendJobData.js
  src/pages/MyCareer/ScrapContentPage/ScrapContentPage.jsx
  src/pages/MyCareer/ScrapContentPage/styled/styled.js
  src/pages/Recommend/JobDetailPage/JobDetailPage.jsx
  src/pages/Recommend/RecommendContentPage/RecommendContentPage.jsx
  src/pages/Recommend/RecommendJobPage/RecommendJobPage.jsx
  src/pages/Recommend/RecommendRouter.jsx
  src/store/useScrapStore.js
Labels: enhancement

#84 [Setting] tanstack-query 설치
  package-lock.json
  package.json
Labels: documentation
