Repository Career-Mate/Web, pull requests merged in 2025-02, with the labels that each got.

#89 [Feat] recommendJob, recommendContent api
  src/apis/Content/ContentApi.js
  src/apis/Job/JobApi.js
  src/apis/Job/useJobApi.js
  src/assets/Card/backend.png
  src/assets/Card/design.png
  src/assets/Card/frontend.png
  src/assets/Card/pm.png
  src/assets/Pagination/arrow-first.svg
  src/assets/Pagination/arrow-last.svg
  src/assets/Pagination/arrow-next.svg
  src/assets/Pagination/arrow-prev.svg
  src/components/common/Button/DeadlineButton/styled/styled.js
  src/components/common/Card/JobPostingCard/JobPostingCard.jsx
  src/components/common/Pagination/Pagination.jsx
  src/components/common/Pagination/styled/styled.js
  src/pages/Recommend/RecommendContentPage/RecommendContentPage.jsx
  src/pages/Recommend/RecommendJobPage/RecommendJobPage.jsx
  src/utils/mapRecommendContentData.js
  src/utils/mapRecommendJobData.js
Labels: enhancement

#87 [Feat] (Api) 로그인 페이지 버튼 연결 및 임시 로그인 파일 제거
  src/App.jsx
  src/components/common/Menu/Navbar/Navbar.jsx
  src/hooks/useLogin.js
  src/hooks/useLoginPopUp.js
  src/pages/Main/LoginPage/LoginPage.jsx
  src/pages/Main/LoginProgressPage/LoginProgressPage.jsx
  src/pages/Main/LoginProgressPage/styled/styled.js
  src/pages/Main/LoginSuccessPage/LoginSuccessPage.jsx
Labels: enhancement

#102 [Feature] (api) JobDetailPage api 연동(2차)
  src/apis/JobDetail/useJobDetailApi.js
  src/assets/JobDetailPage/rabbit-logo.svg
  src/pages/Recommend/JobDetailPage/JobDetailPage.jsx
  src/pages/Recommend/JobDetailPage/styled/styled.js
Labels: duplicate, enhancement

#86 [Feature] (Api) SmartPlanner Page
  src/apis/smartPlanner/SmartPlannerApi.js
  src/apis/smartPlanner/useSmartPlannerApi.js
  src/components/SmartPlanner/SmartPlanner.jsx
  src/components/SmartPlanner/useSmartPlanner.js
  src/components/common/Input/CalendarInput/CalendarInput.jsx
  src/components/common/Templates/SmartTemplate/SmartTemplate.jsx
  src/components/common/Templates/SmartTemplate/styled/styled.js
  src/components/common/Templates/TextTemplate/TextTemplate.jsx
  src/components/common/Templates/TextTemplate/styled/styled.js
  src/components/common/Templates/UserTemplate/Template.jsx
  src/components/common/Templates/UserTemplate/styled/styled.js
  src/data/smartTemplateData.js
  src/hooks/useSmartPlanner.js
  src/pages/Career/FinalSummaryPage/FinalSummaryPage.jsx
  src/pages/Career/InternExperiencePage/InternExperiencePage.jsx
  src/pages/Career/OtherExperiencePage/OtherExperiencePage.jsx
  src/pages/Career/ProjectExperiencePage/ProjectExperiencePage.jsx
  src/pages/Career/SkillsPage/SkillsPage.jsx
  src/pages/MyCareer/SmartPlannerPage/SmartPlannerPage.jsx
  src/utils/SmartPlanner/plannerHandler.js
  src/utils/SmartPlanner/plannerMappers.js
Labels: enhancement

#104 [Feature] JobDetailPage 수정
  src/pages/Recommend/JobDetailPage/styled/styled.js
Labels: duplicate

#105 [Feat] LoginSuccessPage 조건 제거 및 로그아웃 api
  src/apis/Auth/AuthApi.js
  src/apis/Auth/useAuthApi.js
  src/pages/Main/LoginSuccessPage/LoginSuccessPage.jsx
Labels: duplicate

#106 [FEATURE] SmartPlannerPage 태블릿 반응형 UI
  src/components/common/Menu/SubMenu/styled/styled.js
  src/components/common/Templates/SmartTemplate/styled/styled.js
  src/pages/MyCareer/MyCareerPage/styled/styled.js
  src/pages/MyCareer/SmartPlannerPage/styled/styled.js
Labels: enhancement

#90 [Feat] (Api) ProfileSettingPage, ProfileEditPage 연결
  src/apis/Auth/authApi.js
  src/apis/Auth/useAuthApi.js
  src/apis/Profile/profileApi.js
  src/apis/Profile/useProfileApi.js
  src/components/common/Button/LogoutButton/LogoutButton.jsx
  src/components/common/Menu/Navbar/Navbar.jsx
  src/components/common/Popups/ProfilePopup/ProfilePopup.jsx
  src/components/common/Popups/ProfilePopup/styled/styled.js
  src/components/common/ProfileSetting/ProfileSetting.jsx
  src/data/profileData.js
  src/hooks/useProfile.js
  src/hooks/useSelectDrop.js
  src/pages/Career/CareerMainPage/CareerMainPage.jsx
  src/pages/Main/LoginSuccessPage/LoginSuccessPage.jsx
  src/pages/Main/MainPage/MainPage.jsx
  src/pages/Main/MainPage/styled/styled.js
  src/pages/Main/ProfileSettingPage/ProfileSettingPage.jsx
  src/pages/MyCareer/ProfileEditPage/ProfileEditPage.jsx
  src/pages/MyCareer/ProfileEditPage/useProfileEdit.js
  src/pages/Recommend/RecommnedMainPage/RecommendMainPage.jsx
  src/store/authStore.js
  src/utils/Profile/ProfileMapper.js
Labels: enhancement

#93 [Feat] 커리어 템플릿 CRUD 구현
  package-lock.json
  src/App.jsx
  src/apis/Auth/authApi.js
  src/apis/CareerTemplate/templateApi.js
  src/components/common/Templates/TextTemplate/TextTemplate.jsx
  src/components/common/Templates/TextTemplate/styled/styled.js
  src/components/common/Templates/UserTemplate/Template.jsx
  src/components/common/Templates/UserTemplate/styled/styled.js
  src/data/jobTemplateData.js
  src/data/textTemplateData.js
  src/hooks/useCareerSummary.js
  src/hooks/useTemplateData.js
  src/pages/Career/CareerMainPage/CareerMainPage.jsx
  src/pages/Career/CareerSavePage/CareerSavePage.jsx
  src/pages/Career/FinalSummaryPage/FinalSummaryPage.jsx
  src/pages/Career/FinalSummaryPage/useFinalSummary.js
  src/pages/Career/InternExperiencePage/InternExperiencePage.jsx
  src/pages/Career/InternExperiencePage/useInternExperience.js
  src/pages/Career/OtherExperiencePage/OtherExperiencePage.jsx
  src/pages/Career/OtherExperiencePage/useOtherExperience.js
  src/pages/Career/ProjectExperiencePage/ProjectExperiencePage.jsx
  src/pages/Career/ProjectExperiencePage/useProjectExperience.js
  src/pages/Career/SkillsPage/SkillsPage.jsx
  src/pages/Career/SkillsPage/useSkills.js
  src/store/useJobStore.js
  src/store/useTemplateStore.js
Labels: enhancement

#107 [FEATURE] footer 태블릿, 모바일 반응형 UI
  src/apis/Auth/AuthApi.js
  src/components/common/Footer/Footer.jsx
  src/components/common/Footer/styled/styled.js
  src/hooks/useIsMobileScreen.js
Labels: enhancement

#103 [Fix] MainPage 디자인 수정
  src/apis/Auth/AuthApi.js
  src/assets/common/career-mate.svg
  src/components/common/Menu/Navbar/styled/styled.js
  src/pages/Main/MainPage/MainPage.jsx
  src/pages/Main/MainPage/styled/styled.js
Labels: duplicate

#110 [Feature] smartPlannerPage 모바일 반응형 UI & MobileTextarea 공용 컴포넌트 개발
  src/assets/common/help.svg
  src/components/SmartPlanner/SmartPlanner.jsx
  src/components/SmartPlanner/styled/styled.js
  src/components/common/Button/SquareButton/SquareButton.jsx
  src/components/common/Button/SquareButton/styled/styled.js
  src/components/common/Input/CalendarInput/CalendarInput.jsx
  src/components/common/Input/CalendarInput/styled/styled.js
  src/components/common/MobileTextarea/MobileTextarea.jsx
  src/components/common/MobileTextarea/styled/styled.js
  src/components/common/Templates/SmartMobileTemplate/SmartMobileTemplate.jsx
  src/components/common/Templates/SmartMobileTemplate/styled/styled.js
  src/components/common/Templates/SmartTemplate/SmartTemplate.jsx
  src/hooks/useSmartPlanner.js
  src/pages/MyCareer/MyCareerPage/MyCareerPage.jsx
  src/pages/MyCareer/SmartPlannerPage/SmartPlannerPage.jsx
  src/pages/MyCareer/SmartPlannerPage/styled/styled.js
  src/utils/SmartPlanner/plannerHandler.js
Labels: documentation

#120 [FEAT] TemplateCategory 컴포넌트 구현
  src/components/common/ProgressBar/ProgressBar.jsx
  src/components/common/ProgressBar/styled/styled.js
  src/components/common/Templates/TemplateCategory/TemplateCategory.jsx
  src/components/common/Templates/TemplateCategory/styled/styled.js
Labels: enhancement

#111 [Style] JobDetailPage 반응형 UI 구현
  src/apis/JobDetail/useJobDetailApi.js
  src/assets/JobDetailPage/company.svg
  src/components/Recommend/JobDetailList/styled/styled.js
  src/main.jsx
  src/pages/Recommend/JobDetailPage/JobDetailPage.jsx
  src/pages/Recommend/JobDetailPage/styled/styled.js
Labels: documentation

#117 [Fix] SmartPlannerPage 오류 수정
  public/assets/mobile-speech-bubble.svg
  public/assets/rabbit-logo.svg
  public/assets/speech-bubble.svg
  src/components/common/Button/SquareButton/SquareButton.jsx
  src/components/common/Button/SquareButton/styled/styled.js
  src/components/common/Input/CalendarInput/styled/styled.js
  src/components/common/Input/styled/styled.js
  src/pages/MyCareer/MyCareerPage/styled/styled.js
  src/pages/MyCareer/SmartPlannerPage/SmartPlannerPage.jsx
  src/pages/MyCareer/SmartPlannerPage/styled/styled.js
  src/pages/Recommend/JobDetailPage/JobDetailPage.jsx
  src/pages/Recommend/JobDetailPage/styled/styled.js
Labels: bug

#98 [Feat] scrap api
  src/App.jsx
  src/apis/Content/ContentApi.js
  src/apis/Job/JobApi.js
  src/apis/Job/useJobApi.js
  src/apis/Scrap/Content/ContentScrapApi.js
  src/apis/Scrap/Job/JobScrapApi.js
  src/components/common/Button/DeadlineButton/styled/styled.js
  src/components/common/Button/OvalButton/styled/styled.js
  src/components/common/Card/ContentCard/ContentCard.jsx
  src/components/common/Card/JobPostingCard/JobPostingCard.jsx
  src/components/common/Card/styled/styled.js
  src/components/common/Pagination/MobilePagination/MobilePagination.js
  src/components/common/Pagination/MobilePagination/styled/styled.js
  src/components/common/Pagination/Pagination.jsx
  src/components/common/Pagination/Pagination/Pagination.jsx
  src/components/common/Pagination/Pagination/styled/styled.js
  src/components/common/Popups/LoadingPopup/LoadingPopup.jsx
  src/data/recommendContentData.js
  src/data/recommendJobData.js
  src/hooks/usePagination.js
  src/pages/Career/CareerMainPage/CareerMainPage.jsx
  src/pages/Career/CareerSavePage/CareerSavePage.jsx
  src/pages/MyCareer/ScrapContentPage/ScrapContentPage.jsx
  src/pages/MyCareer/ScrapContentPage/styled/styled.js
  src/pages/MyCareer/ScrapPage/ScrapContent.jsx
  src/pages/MyCareer/ScrapPage/ScrapJob.jsx
  src/pages/MyCareer/ScrapPage/ScrapPage.jsx
  src/pages/MyCareer/ScrapPage/styled/styled.js
  src/pages/Recommend/JobDetailPage/JobDetailPage.jsx
  src/pages/Recommend/RecommendContentPage/RecommendContentPage.jsx
  src/pages/Recommend/RecommendContentPage/styled/styled.js
  src/pages/Recommend/RecommendJobPage/RecommendJobPage.jsx
  src/pages/Recommend/RecommendJobPage/styled/styled.js
  src/pages/Recommend/RecommendPage/RecommendContentPage.jsx
  src/pages/Recommend/RecommendPage/RecommendJobPage.jsx
  src/pages/Recommend/RecommendPage/RecommendPage.jsx
  src/pages/Recommend/RecommendPage/styled/styled.js
  src/pages/Recommend/RecommnedMainPage/RecommendMainPage.jsx
  src/store/useScrapStore.js
  src/utils/mapRecommendJobData.js
Labels: enhancement

#124 [Style] 커리어 정리하기 전체 페이지 태블릿 버전 UI 구현
  src/components/common/Templates/TextTemplate/styled/styled.js
  src/components/common/Templates/UserTemplate/Template.jsx
  src/components/common/Templates/UserTemplate/styled/styled.js
  src/pages/Career/CareerMainPage/styled/styled.js
  src/pages/Career/CareerPage/styled/styled.js
  src/pages/Career/CareerSavePage/styled/styled.js
  src/pages/Career/FinalSummaryPage/styled/styled.js
  src/pages/Career/InternExperiencePage/styled/styled.js
  src/pages/Career/OtherExperiencePage/styled/styled.js
  src/pages/Career/ProjectExperiencePage/styled/styled.js
  src/pages/Career/SkillsPage/styled/styled.js
Labels: enhancement

#122 [Style] Navbar 반응형 UI
  src/assets/Navbar/account_circle.svg
  src/assets/Navbar/career.svg
  src/assets/Navbar/detail.svg
  src/assets/Navbar/drop-down.svg
  src/assets/Navbar/drop-up.svg
  src/assets/Navbar/hamburger-menu.svg
  src/assets/Navbar/home.svg
  src/assets/Navbar/keep.svg
  src/assets/close.svg
  src/components/common/Menu/MobileNavbar/MobileNavbar.jsx
  src/components/common/Menu/MobileNavbar/styled/styled.js
  src/components/common/Menu/Navbar/Navbar.jsx
  src/components/common/Menu/Navbar/styled/styled.js
Labels: enhancement

#99 [Feature] Skeleton UI 구현
  src/components/SkeletonUi/ContentCardSkeleton/ContentCardSkeleton.jsx
  src/components/SkeletonUi/ContentCardSkeleton/styled/styled.js
  src/components/SkeletonUi/JobDetailListSkeleton/JobDetailListSkeleton.jsx
  src/components/SkeletonUi/JobDetailListSkeleton/styled/styled.js
  src/components/SkeletonUi/JobDetailSkeleton/JobDetailSkeleton.jsx
  src/components/SkeletonUi/JobDetailSkeleton/styled/styled.js
  src/components/SkeletonUi/JobPostingCardSkeleton/JobPostingCardSkeleton.jsx
  src/components/SkeletonUi/JobPostingCardSkeleton/styled/styled.js
  src/hooks/useIsMobileScreen.js
  src/pages/Recommend/JobDetailPage/JobDetailPage.jsx
  src/pages/Recommend/RecommendPage/RecommendContentPage.jsx
  src/pages/Recommend/RecommendPage/RecommendJobPage.jsx
Labels: enhancement

#123 [Style] MainPage 반응형 UI
  src/components/MainPage/Card/styled/styled.js
  src/components/MainPage/CheckTextBox/CheckTextBox.jsx
  src/components/MainPage/CheckTextBox/styled/styled.js
  src/components/MainPage/InterviewBox/InterviewBox.jsx
  src/components/MainPage/InterviewBox/styled/styled.js
  src/components/common/Button/OvalButton/styled/styled.js
  src/pages/Main/MainPage/MainPage.jsx
  src/pages/Main/MainPage/styled/styled.js
Labels: enhancement

#126 [Style] smartPlanner 모바일 UI 수정
  src/components/SmartPlanner/SmartPlanner.jsx
  src/components/common/Button/SquareButton/styled/styled.js
  src/components/common/Footer/styled/styled.js
  src/components/common/Input/CalendarInput/styled/styled.js
  src/components/common/MobileTextarea/MobileTextarea.jsx
  src/components/common/Templates/SmartMobileTemplate/SmartMobileTemplate.jsx
  src/components/common/Templates/SmartMobileTemplate/styled/styled.js
  src/hooks/useIsMobileScreen.js
  src/pages/MyCareer/MyCareerPage/MyCareerPage.jsx
  src/pages/MyCareer/MyCareerPage/styled/styled.js
  src/pages/MyCareer/SmartPlannerPage/SmartPlannerPage.jsx
  src/pages/MyCareer/SmartPlannerPage/styled/styled.js
Labels: documentation

#127 [Style] JobDetail 및 skeletonUI 모바일 UI 변경
  src/components/Recommend/JobDetailList/styled/styled.js
  src/components/SkeletonUi/ContentCardSkeleton/styled/styled.js
  src/components/SkeletonUi/JobDetailListSkeleton/styled/styled.js
  src/components/SkeletonUi/JobDetailSkeleton/styled/styled.js
  src/components/SkeletonUi/JobPostingCardSkeleton/styled/styled.js
  src/pages/Recommend/JobDetailPage/styled/styled.js
Labels: documentation

#125 [Style] Card 컴포넌트 반응형 UI
  src/components/common/Card/ContentCard/ContentCard.jsx
  src/components/common/Card/JobPostingCard/JobPostingCard.jsx
  src/components/common/Card/styled/styled.js
Labels: enhancement

#128 [Style] pagination 모바일 UI
  src/components/common/Pagination/Pagination/styled/styled.js
Labels: documentation

#139 [Style] 커리어 정리하기 전체 페이지 모바일 버전 UI 구현
  src/components/common/Pagination/MobilePagination/MobilePagination.js
  src/components/common/Pagination/MobilePagination/styled/styled.js
  src/components/common/ProgressBar/styled/styled.js
  src/components/common/Templates/TemplateCategory/TemplateCategory.jsx
  src/components/common/Templates/TemplateCategory/styled/styled.js
  src/components/common/Templates/TextTemplate/TextTemplate.jsx
  src/components/common/Templates/TextTemplate/styled/styled.js
  src/components/common/Templates/UserTemplate/Template.jsx
  src/components/common/Templates/UserTemplate/styled/styled.js
  src/pages/Career/CareerMainPage/CareerMainPage.jsx
  src/pages/Career/CareerMainPage/styled/styled.js
  src/pages/Career/CareerSavePage/CareerSavePage.jsx
  src/pages/Career/CareerSavePage/styled/styled.js
  src/pages/Career/FinalSummaryPage/FinalSummaryPage.jsx
  src/pages/Career/FinalSummaryPage/styled/styled.js
  src/pages/Career/InternExperiencePage/InternExperiencePage.jsx
  src/pages/Career/InternExperiencePage/styled/styled.js
  src/pages/Career/OtherExperiencePage/OtherExperiencePage.jsx
  src/pages/Career/OtherExperiencePage/styled/styled.js
  src/pages/Career/ProjectExperiencePage/ProjectExperiencePage.jsx
  src/pages/Career/ProjectExperiencePage/styled/styled.js
  src/pages/Career/SkillsPage/SkillsPage.jsx
  src/pages/Career/SkillsPage/styled/styled.js
Labels: enhancement

#134 [Feat] useFetchProfile에 enable=isLogin 설정
  src/apis/Profile/useProfileApi.js
  src/pages/Main/MainPage/MainPage.jsx
Labels: duplicate

#140 [Refactor] smart planner page 리팩토링
  src/components/SmartPlanner/SmartPlanner.jsx
  src/components/SmartPlanner/styled/styled.js
  src/components/common/TemplateTextarea/TemplateTextarea.jsx
  src/components/common/TemplateTextarea/styled/styled.js
  src/components/common/Templates/SmartMobileTemplate/SmartMobileTemplate.jsx
  src/components/common/Templates/SmartMobileTemplate/styled/styled.js
  src/components/common/Templates/SmartTemplate/SmartTemplate.jsx
  src/components/common/Templates/SmartTemplate/styled/styled.js
Labels: documentation

#142 [Style] MainPage OtherBox width 제거 및 SecondPage padding-top 수정
  src/pages/Main/MainPage/styled/styled.js
Labels: duplicate

#138 [Style] Jobdetail pc UI변경
  src/pages/Recommend/JobDetailPage/JobDetailPage.jsx
  src/pages/Recommend/JobDetailPage/styled/styled.js
Labels: enhancement

#143 [Style] smart planner page(Calendar 수정)
  src/components/common/Input/CalendarInput/CalendarInput.jsx
  src/components/common/Input/CalendarInput/styled/styled.js
  src/components/common/Input/CalendarPicker/CalendarPicker.jsx
  src/components/common/Input/CalendarPicker/styled/styled.js
Labels: enhancement

#137 [Style] Profile page 반응형 UI
  src/apis/Profile/useProfileApi.js
  src/components/SmartPlanner/SmartPlanner.jsx
  src/components/common/Input/ProfileInput.jsx
  src/components/common/Input/SelectDropInput/SelectDropInput.jsx
  src/components/common/Input/SelectDropInput/styled/styled.js
  src/components/common/Input/styled/styled.js
  src/components/common/Menu/Navbar/Navbar.jsx
  src/components/common/ProfileSetting/ProfileSetting.jsx
  src/components/common/ProfileSetting/styled/styled.js
  src/pages/Main/MainPage/styled/styled.js
  src/pages/Main/ProfileSettingPage/ProfileSettingPage.jsx
  src/pages/Main/ProfileSettingPage/styled/styled.js
  src/pages/MyCareer/ProfileEditPage/ProfileEditPage.jsx
  src/pages/MyCareer/ProfileEditPage/styled/styled.js
Labels: enhancement

#152 [Feature]progress bar 이동 기능 추가
  src/components/common/ProgressBar/ProgressBar.jsx
  src/components/common/ProgressBar/styled/styled.js
  src/pages/Career/FinalSummaryPage/FinalSummaryPage.jsx
  src/pages/Career/InternExperiencePage/InternExperiencePage.jsx
  src/pages/Career/OtherExperiencePage/OtherExperiencePage.jsx
  src/pages/Career/ProjectExperiencePage/ProjectExperiencePage.jsx
  src/pages/Career/SkillsPage/SkillsPage.jsx
Labels: enhancement

#153 [Fix] 커리어 정리하기 iOS 오류 해결 및 리팩토링
  src/components/common/Input/CalendarPicker/CalendarPicker.jsx
  src/components/common/Input/CalendarPicker/styled/styled.js
  src/components/common/TemplateTextarea/TemplateTextarea.jsx
  src/components/common/TemplateTextarea/styled/styled.js
  src/components/common/Templates/UserTemplate/Template.jsx
  src/components/common/Templates/UserTemplate/styled/styled.js
  src/store/useTemplateStore.js
Labels: bug

#154 [Feat] SelectDropInput 옵션 선택 취소
  src/components/common/Input/SelectDropInput/SelectDropInput.jsx
  src/hooks/useSelectDrop.js
  src/pages/Main/ProfileSettingPage/ProfileSettingPage.jsx
Labels: bug
